spring.application.name=STS_RestAPI_JPA_JSON_DB
spring.datasource.url=jdbc:mysql://localhost:3306/sts
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true